// export const chat = [{
//     _id: "1",
//     name: "John Doe",
//     avatar: ["https://example.com/avatar1.jpg"],
//     members: ["1", "2", "3", "4", "5", "6"],
//     groupChat: false,
// }]

export const chat = [
    {
      _id: "1",
      name: "John Doe",
      avatar: ["https://example.com/avatar1.jpg"],
      members: ["1", "2", "3", "4", "5", "6"],
      groupChat: false,
    },
    {
      _id: "2",
      name: "Jane Smith",
      avatar: ["https://example.com/avatar2.jpg"],
      members: ["7", "8", "9"],
      groupChat: false,
    },
    {
      _id: "3",
      name: "Development Team",
      avatar: ["https://example.com/group-avatar1.jpg"],
      members: ["10", "11", "12", "13", "14"],
      groupChat: true,
    },
    {
      _id: "4",
      name: "Project Alpha",
      avatar: ["https://example.com/group-avatar2.jpg"],
      members: ["15", "16", "17", "18"],
      groupChat: true,
    },
    {
      _id: "5",
      name: "Alice Cooper",
      avatar: ["https://example.com/avatar3.jpg"],
      members: ["19", "20"],
      groupChat: false,
    },
    {
      _id: "6",
      name: "Marketing Team",
      avatar: ["https://example.com/group-avatar3.jpg"],
      members: ["21", "22", "23", "24", "25"],
      groupChat: true,
    },
    {
      _id: "7",
      name: "Bob Marley",
      avatar: ["https://example.com/avatar4.jpg"],
      members: ["26", "27"],
      groupChat: false,
    },
    {
      _id: "8",
      name: "Sales Team",
      avatar: ["https://example.com/group-avatar4.jpg"],
      members: ["28", "29", "30", "31", "32"],
      groupChat: true,
    },
    {
      _id: "9",
      name: "Emily Watson",
      avatar: ["https://example.com/avatar5.jpg"],
      members: ["33", "34"],
      groupChat: false,
    },
    {
      _id: "10",
      name: "Project Beta",
      avatar: ["https://example.com/group-avatar5.jpg"],
      members: ["35", "36", "37", "38"],
      groupChat: true,
    },
    {
      _id: "11",
      name: "Charlie Daniels",
      avatar: ["https://example.com/avatar6.jpg"],
      members: ["39", "40"],
      groupChat: false,
    },
    {
      _id: "12",
      name: "HR Department",
      avatar: ["https://example.com/group-avatar6.jpg"],
      members: ["41", "42", "43", "44"],
      groupChat: true,
    },
    {
      _id: "13",
      name: "Olivia Johnson",
      avatar: ["https://example.com/avatar7.jpg"],
      members: ["45", "46"],
      groupChat: false,
    },
    {
      _id: "14",
      name: "Engineering Team",
      avatar: ["https://example.com/group-avatar7.jpg"],
      members: ["47", "48", "49", "50"],
      groupChat: true,
    },
    {
      _id: "15",
      name: "Sophia Lee",
      avatar: ["https://example.com/avatar8.jpg"],
      members: ["51", "52"],
      groupChat: false,
    },
    {
      _id: "16",
      name: "Support Team",
      avatar: ["https://example.com/group-avatar8.jpg"],
      members: ["53", "54", "55", "56", "57"],
      groupChat: true,
    },
    {
      _id: "17",
      name: "David Miller",
      avatar: ["https://example.com/avatar9.jpg"],
      members: ["58", "59"],
      groupChat: false,
    },
    {
      _id: "18",
      name: "Finance Team",
      avatar: ["https://example.com/group-avatar9.jpg"],
      members: ["60", "61", "62", "63", "64"],
      groupChat: true,
    },
    {
      _id: "19",
      name: "Liam Brown",
      avatar: ["https://example.com/avatar10.jpg"],
      members: ["65", "66"],
      groupChat: false,
    },
    {
      _id: "20",
      name: "Legal Team",
      avatar: ["https://example.com/group-avatar10.jpg"],
      members: ["67", "68", "69", "70"],
      groupChat: true,
    }
  ];